config/routes.rb
Rails.application.routes.draw do

  

  get 'users/new'

  root 'pages#home'
  get 'pages/home'

  get 'pages/resume'
  get 'pages/about'

  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	validates :commenter, presence: true, length: {minimum: 5}
end

app/models/post.rb
class Post < ActiveRecord::Base
	# dependent: :destroy will delete all comments associated with a deleted post
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}

end

app/models/user.rb
class User < ActiveRecord::Base
	# the class User inherits from ActiveRecord::Base (User model has all its functionality)

	# presence: true is an options hash, validates is a method

	validates :name,  presence: true, length: { maximum: 50 }

	# an email is valid only if it matches the VALID_EMAIL_REGEX format
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # in order to create a new comment, we need to find which post we are currently viewing
    @post = Post.find(params[:post_id])
    # a new comment is created for the specific post we found above
    @comment = @post.comments.create(comment_params)
    # after the comment is created, we redirect to show the post that the comment was created on
    redirect_to post_path(@post)
  end

  def destroy
    # find the ID of the post we want to destroy
    @post = Post.find(params[:post_id])
    # find the ID of the comment within the post that we want to find
    @comment = @post.comments.find(params[:id])
    # destroy the comment
    @comment.destroy
    # after the comment is destroyed, we redirect to show the post (the deleted comment has disappeared)
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	# these are all static pages, they need methods for them in order for rails routes to know what view to render
	def home
	end

	def resume
	end
	def about
	end

	def contact
	end
	def blog
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	# R of crud
	def index
		@posts = Post.all
	end
	# R of crud
	def show
		@post = Post.find(params[:id])

	end

	# C of crud
	def new
		@post = Post.new
	end

	# U of crud
	def edit
  	@post = Post.find(params[:id])
	end

	# C of crud
	# create action is sending the new blog post to the database
	def create
		#render plain: params[:post].inspect
		@post = Post.new(post_params)
		if @post.save
			redirect_to :action => 'show', :id => @post.id
		else
			render 'new'
		end
	end

	# U of crud
	def update
		@post = Post.find(params[:id])
 
  	if @post.update(post_params)
    	redirect_to @post
  	else
    	render 'edit'
  	end
	end

	# D of crud
	def destroy
  	@post = Post.find(params[:id])
  	@post.destroy
 
  	redirect_to posts_path
	end



	private
		def post_params
			params.require(:post).permit(:title, :text)
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>


<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PortfolioWebsite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<p> about me </p>

<%= link_to 'Back to home', root_path %>

app/views/pages/home.html.erb
<p> Homepage </p>
<p> hello my name is ben </p>



<%= link_to 'my resume', :controller => 'pages', :action => 'resume' %>
<%= link_to 'My Resume', pages_resume_path %>


<%= link_to 'about me', :controller => 'pages', :action => 'about' %>

<%= link_to 'newblogpost', :controller => 'posts', :action => 'new' %>



<%= link_to 'allblogposts', :controller => 'posts', :action => 'index' %>
<%= link_to 'My Blog', controller: 'posts' %>

		<!-- link_to 'View Transcript', 
    :controller => 'podcast', 
    :action => 'view_transcript', 
    :id => podcast %> -->

app/views/pages/resume.html.erb
<p> my resume </p>

<%= link_to 'Back to home', root_path %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>
 
<%= render 'form' %>

 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing all blog posts</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @posts.each do |k| %>
    <tr>
      <td><%= k.title %></td>
      <td><%= k.text %></td>
      <td><%= link_to 'Show', post_path(k) %></td>
      <td><%= link_to 'Edit', edit_post_path(k) %></td>
      <td><%= link_to 'Destroy', post_path(k),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back to home', root_path %>

app/views/posts/new.html.erb
<h3> hello, new blog post </h3>

<%= render 'form' %>


<%= link_to 'Back to home', root_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>


<h2>Comments</h2>
<%= render @post.comments %>
 

<h2>Add a comment:</h2>
<%= render 'comments/form' %>





<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Back', posts_path %>
<%= link_to 'Back to home', root_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>